package it.uniroma3.epsl2.deliberative.search;

/**
 * 
 * @author anacleto
 *
 */
public enum SearchStrategyType {

	/**
	 * "Classical" Depth First search strategy
	 */
	DFS(DepthFirstSearchStrategy.class.getName()),
	
	/**
	 * Depth first search strategy enriched with minimum-degree selection, Namely given 
	 * two nodes at the same depth the strategy selects the node with less siblings... i.e.
	 * the node generated by the flaw with less solutions
	 */
	DFD(DepthFirstDegreeSearchStrategy.class.getName());
	
	private String cname;
	
	/**
	 * 
	 * @param cname
	 */
	private SearchStrategyType(String cname) {
		this.cname = cname;
	}
	
	/**
	 * 
	 * @return
	 */
	public String getStrategyClassName() {
		return this.cname;
	}
}
